n=input("Enter your name ")
a=input("Enter your age ")
r=input("Enter your roll_number ")
p=input("Enter your phone_number ")
print("My name is", n)
print("My age is", a)
print("My roll_number is", r)
print("My phone_number is", p)
